### ISSUE TITLE
Hashes strings wrong

### ISSUE THREAD

**Issue by jamen** [emilbayes/blake2b#5]
Hi. I noticed hashing strings is incorrect. It hashes the zeroed input buffer instead:

```js
blake2b(16).update('a').digest('hex')
// '7025e075d5e2f6cde3cc051a31f07660'

blake2b(16).update('b').digest('hex')
// '7025e075d5e2f6cde3cc051a31f07660'

blake2b(16).update(new Uint8Array(1)).digest('hex')
// '7025e075d5e2f6cde3cc051a31f07660'
```

Based on `hash.update` and `blake2bUpdate`, the effect seems to be like:

```js
const arr = new Uint8Array(1)
arr[0] = 'a'
// that does nothing:
// arr[0] === 0
blake2b(16).update(arr).digest('hex')
// '7025e075d5e2f6cde3cc051a31f07660'
```

Related to this issue is hashing empty strings:

```js
blake2b(16).update('').digest('hex')
// Error: input must be TypedArray or Buffer
```

Maybe this assert was intended for all strings, and not just the empty one? It could also use `TextEncoder` and `Buffer.from` for you.

**Comment by emilbayes** [comment]
@jamen I should better this assert: https://github.com/emilbayes/blake2b/blob/master/index.js#L214

So this module does not support strings, only TypedArrays and Node Buffers

**Comment by jamen** [comment]
I gave it a shot. If you have a better way I can do that.

**Comment by divinity76** [comment]
can't we just add support to ease usability? 
```js
if(typeof(input)==="string"){input=(new TextEncoder()).encode(input);}
```

(yeah i know the check makes the code a bit slower but it should be only be like a millisecond of difference per invocation for existing code on modern hardware)
