### ISSUE TITLE
Expected hex length

### ISSUE THREAD

**Issue by jshjohnson** [emilbayes/blake2b#7]
Hey 👋 

Is it expected that the returned hex length is double the `outLength` passed to `blake2b()`? 

I would have assumed if I ran the following, I would get a hex string with a length of 32 but it returns a string with a length of 64:

```js
const input = Buffer.from(value);
const hashedValue = blake2b(32)
  .update(input)
  .digest('hex');

return hashedValue;
```

**Comment by emilbayes** [comment]
You do get a hex string of *byte length* 32, but as each "data" byte in hex takes two "string" bytes, hex representation will always be double the size

**Comment by emilbayes** [comment]
Example: `FF` represents the integer `255` which fits in a single byte as `11111111`, but as you just saw, I had to use two characters to represent that. If you want a 32 byte output, you can either pass nothing to `.digest()` or pass a `new Uint8Array(32)`

**Comment by jshjohnson** [comment]
Cool, thanks 👍
